OPTIONS (SKIP=1)
LOAD DATA
INFILE 'episode.csv'
APPEND
INTO TABLE Episode
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(id_episode INTEGER EXTERNAL, numero_episode INTEGER EXTERNAL, numero_saison INTEGER EXTERNAL, id_serie INTEGER EXTERNAL, duree INTEGER EXTERNAL)
