OPTIONS (SKIP=1)
LOAD DATA
INFILE 'prends.csv'
APPEND
INTO TABLE Prends
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(id_utilisateur INTEGER EXTERNAL, id_abonnement INTEGER EXTERNAL,
debut_abonnement DATE "YYYY-MM-DD")
