OPTIONS (SKIP=1)
LOAD DATA
INFILE 'serie.csv'
APPEND
INTO TABLE Serie
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(id_serie INTEGER EXTERNAL, titre CHAR(100), annee_apparition INTEGER EXTERNAL, pays_production CHAR(50), limite_age INTEGER EXTERNAL)
