OPTIONS (SKIP=1)
LOAD DATA
INFILE 'telecharge.csv'
APPEND
INTO TABLE Telecharge
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(id_telechargement INTEGER EXTERNAL, date_telechargement DATE "YYYY-MM-DD", id_utilisateur INTEGER EXTERNAL, id_film INTEGER EXTERNAL NULLIF id_film=BLANKS, id_episode INTEGER EXTERNAL NULLIF id_episode=BLANKS)
