OPTIONS (SKIP=1)
LOAD DATA
INFILE 'visionne.csv'
APPEND
INTO TABLE Visionne
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(id_visionnage INTEGER EXTERNAL, date_visionnage DATE "YYYY-MM-DD", duree_visionnage INTEGER EXTERNAL, likes INTEGER EXTERNAL, id_utilisateur INTEGER EXTERNAL, id_film INTEGER EXTERNAL NULLIF id_film=BLANKS, id_episode INTEGER EXTERNAL NULLIF id_episode=BLANKS)
