CREATE SEQUENCE seq_utilisateur  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_abonnement   START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_film         START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_serie        START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_episode      START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_visionne     START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_telecharge   START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_realisateur  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_acteur       START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_personnage   START WITH 1 INCREMENT BY 1;

-- Exemple d'utilisation --

INSERT INTO Film VALUES (seq_film.NEXTVAL, 'Film_test', 2020, 'France', 120, 12);